name: Hello

on:
  push:
    branches:
      - 'main'
      pull_request:
        branches:
          - 'main'

  jobs:
    newWorld: 
    runs-on: ubuntu-latest

    steps:
      - name: apple
      run: echo "Hello World"
