name: Hello

on:
  issues:
   types:
     - opened


jobs:
  newWorld: 
    runs-on: ubuntu-latest

    steps:
     - name: apple
       run: echo '${{ toJSON(github.event) }}' | jq 
     - name: number
       run: echo '${{ github.event.issue.number }}'
     - name: Create comment
       uses: peter-evans/create-or-update-comment@v3
       with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown**   
