name: hi
on:
  push:
      branches:
        - 'main'
        
jobs:
   build:
       runs-on: ubuntu-latest
       
       steps:
       - uses: action/checkout@v3
       - name: first
         run: echo ${{ toJSON(github.event) }} | jq 
       
